version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - develop
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./KPCLib/KPCLib.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp2.0/publish
  - cmd: dotnet build ./KPCLib/KPCLib.csproj
after_build:
  # For once the build has completed
  - cmd: dotnet pack ./KPCLib/KPCLib.csproj
artifacts:
  - path: 'KPCLib\bin\Debug\KPCLib.*.nupkg'
    name: KPCLib
#   type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./KPCLib.xunit/KPCLib.xunit.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd KPCLib.xunit
  - cmd: dotnet test
on_finish :
  # any cleanup in here
deploy: off